[package]
name = "kas-wgpu"
version = "0.1.0"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2018"
license = "Apache-2.0"
description = "Native KAS toolkit using wgpu"
keywords = ["gui"]
categories = ["gui"]
repository = "https://github.com/dhardy/kas"

[features]
default = ["clipboard", "font-kit"]

[dependencies]
kas = { path = "..", version = "0.1.0", features = ["winit"] }
glsl-to-spirv = "0.1"
winit = "=0.20.0-alpha5"
wgpu = "0.4.0"
wgpu_glyph = "0.6.0"
font-kit = { version = "0.4.0", optional = true }
lazy_static = "1.4.0"

[dependencies.clipboard]
# Provides clipboard support
version = "0.5"
optional = true

[dev-dependencies]
chrono = "0.4"
