[package]
name = "kas-wgpu"
version = "0.2.1"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2018"
license = "Apache-2.0"
description = "Native KAS toolkit using wgpu"
keywords = ["gui"]
categories = ["gui"]
repository = "https://github.com/dhardy/kas"

[features]
default = ["clipboard", "font-kit"]

[dependencies]
kas = { path = "..", version = "0.2.1", features = ["winit"] }
font-kit = { version = "0.4.0", optional = true }
lazy_static = "1.4.0"
log = "0.4"
shaderc = "0.6.1"
smallvec = "1.1"
wgpu = "0.4.0"
wgpu_glyph = "0.6.0"
winit = { version = "0.20.0" }

[dependencies.clipboard]
# Provides clipboard support
version = "0.5"
optional = true

[dev-dependencies]
chrono = "0.4"
env_logger = "0.7"
