language: rust
sudo: false

# Currently we only support nightly rustc
rust: nightly

script:
  - cargo test --all-features
  - cargo test --manifest-path kas-macros/Cargo.toml --all-features
  - cargo test --manifest-path kas-theme/Cargo.toml --all-features
  - cargo test --manifest-path kas-wgpu/Cargo.toml
  - cargo test --manifest-path kas-wgpu/Cargo.toml --all-features
  - cargo doc --features winit,stack_dst --no-deps
  - cargo doc --manifest-path kas-theme/Cargo.toml --features stack_dst --no-deps
  - cargo doc --manifest-path kas-wgpu/Cargo.toml --features stack_dst --no-deps

matrix:
  include:
    - name: "Linux nightly"
      os: linux
      before_install:
        - sudo apt-get -y install libxcb-shape0-dev libxcb-xfixes0-dev

    - name: "OSX nightly"
      os: osx
      # Note: this has timeout issues testing kas-wgpu, so only use cargo check
      script:
        - cargo test --all-features
        - cargo test --manifest-path kas-macros/Cargo.toml --all-features
        - cargo check --manifest-path kas-theme/Cargo.toml
        - cargo check --manifest-path kas-wgpu/Cargo.toml --examples
        - cargo doc --features winit,stack_dst --no-deps
