[package]
name = "mygui"
version = "0.1.0"
authors = ["Diggory Hardy <git@dhardy.name>"]

[dependencies]
gtk = "0.5"
gdk = "0.9"
glib = "0.6"
gtk-sys = "0.7"
cassowary = { git = "https://github.com/dhardy/cassowary-rs" }
