[package]
name = "kas"
version = "0.1.0"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2018"
license = "Apache-2.0"
description = "GUI Toolkit Abstraction System"
keywords = ["gui"]
categories = ["gui"]
repository = "https://github.com/dhardy/kas"

[features]
# Enables usage of unstable Rust features
nightly = []
# Enables documentation of APIs for toolkits and internal use.
# This API is not intended for use by end-user applications and
# thus is omitted from built documentation by default.
# This flag does not change the API, only built documentation.
internal_doc = []

[dependencies]
log = "0.4"
smallvec = "1.1"

[dependencies.kas-macros]
version = "0.1.0"
path = "kas-macros"

[dependencies.rusttype]
# Dependency for the Font type. This is a temporary measure
# (see notes on Theme::get_fonts).
version = "0.8"

[dependencies.winit]
# Provides translations for several winit types
version = "0.20"
git = "https://github.com/rust-windowing/winit.git" # match kas_wgpu version
optional = true

[workspace]
members = ["kas-macros", "kas-wgpu"]

[package.metadata.docs.rs]
features = ["nightly"]
