[package]
name = "mygui"
version = "0.1.0"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2018"

[features]
# Enable an internal layout solver. Currently this uses Cassowary.
# Not required by all toolkits.
layout = ["cassowary", "mygui-macros/cassowary"]

[dependencies]
cassowary = { git = "https://github.com/dhardy/cassowary-rs", optional = true }
mygui-macros = { version = "0.1", path = "mygui-macros" }

[workspace]
members = ["mygui-gtk", "mygui-macros"]
