[package]
name = "kas"
version = "0.1.0"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2018"

[features]
# Enable an internal layout solver. Currently this uses Cassowary.
# Not required by all toolkits.
layout = ["cassowary", "kas-macros/cassowary"]

[dependencies]
cassowary = { git = "https://github.com/dhardy/cassowary-rs", optional = true }
kas-macros = { version = "0.1", path = "kas-macros" }

[workspace]
members = ["kas-gtk", "kas-macros"]
