[package]
name = "mygui"
version = "0.1.0"
authors = ["Diggory Hardy <git@dhardy.name>"]

[dependencies]
gtk = { version = "0.4.0", path = "../gtk-rs/gtk" }
gdk = { version = "0.8.0", path = "../gtk-rs/gdk" }
