[package]
name = "kas"
version = "0.0.1"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2018"
license = "Apache-2.0"
description = "GUI Toolkit Abstraction System"
keywords = ["gui"]
categories = ["gui"]
repository = "https://gitlab.com/dhardy/mygui"

[features]
# Enable an internal layout solver. Currently this uses Cassowary.
# Not required by all toolkits.
layout = ["cassowary", "kas-macros/cassowary"]

[dependencies]
cassowary = { git = "https://github.com/dhardy/cassowary-rs", optional = true }
kas-macros = { version = "=0.0.1", path = "kas-macros" }

[workspace]
members = ["kas-gtk", "kas-macros"]
