[package]
name = "mygui"
version = "0.1.0"
authors = ["Diggory Hardy <git@dhardy.name>"]

[dependencies]
cassowary = { git = "https://github.com/dhardy/cassowary-rs" }

[workspace]
members = ["mygui-gtk"]
